name: image-builder-custom
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Exec custom shell
      run: |
        curl -fsSL "https://www.qics.top/shell/gitaction/custom.sh" | /bin/sh
    
