name: image-builder-cloudflared
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Exec build shell
      run: |
        curl -fsSL "https://www.qics.top/shell/docker/dockerfiles/cloudflared/cloudflared_builder.sh" | /bin/sh
    
