name: action-call
on:
  workflow_dispatch:
    inputs:
        shell_url:
          required: false
          type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Exec Action Shell
      run: |
        echo "Custom parameter value is ${{ github.event.inputs.shell_url }}"
        curl -fsSL "${{ github.event.inputs.shell_url }}" | /bin/sh
    
