name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }} 
    - name: exec build shell
      run: |
        mkdir /tmp/qics 
        curl -o /tmp/qics/docker_build.sh -L https://www.qics.top/shell/docker/dockerfiles/debian-vnc.sh
        chmod +x /tmp/qics/docker_build.sh
        sh /tmp/qics/docker_build.sh
    
