name: image-builder-linuxall
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }} 
    - name: Exec build shell
      run: |
        docker buildx create --name mutibuilder
        docker buildx use mutibuilder
        docker buildx inspect --bootstrap
        curl -fsSL "https://www.qics.top/shell/docker/dockerfiles/debian/Dockerfile_debian12.sh" | /bin/sh
        docker rmi qics/debian:latest
        curl -fsSL "https://www.qics.top/shell/docker/dockerfiles/debian/Dockerfile_vnc.sh" | /bin/sh
        curl -fsSL "https://www.qics.top/shell/docker/dockerfiles/pickstar/pickstar_builder.sh" | /bin/sh
        curl -fsSL "https://www.qics.top/shell/docker/dockerfiles/kali/docker_kali.sh" | /bin/sh


