name: image-builder-dind
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Exec build shell
      run: |
        curl -fsSL "https://www.qics.top/shell/docker/dockerfiles/dind/dind_builder.sh" | /bin/sh
