name: image-builder-netbird
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Exec build shell
      run: |
        curl -fsSL "https://www.qics.top/shell/docker/dockerfiles/netbird/netbird_builder.sh" | /bin/sh
